@startuml

actor User
control server
database order
database productInOrder

User -> server: PUT /update-order-by-id with request field
activate server
server -> server: Authorize user can udpate order
alt Unauthorize
    server --> User: Return error code 401 and message: User authorize
else Authorize
    server -> order: Find order by Id and update
    activate order
    alt Update fail
        order --> server: Return error message
        server --> User: Error message
    else Update successfully
        order --> server: Return success message
        deactivate order
        server --> User: Success message
    end

    server -> productInOrder: Remove old product in order
    activate productInOrder
    alt Remove fail
        productInOrder --> server: Return error message
        server --> User: Error message
    else Remove successfully
        productInOrder --> server: Return success message
        server --> User: Success message
    end

    server -> productInOrder: Insert new product in order
    alt Insert fail
        productInOrder --> server: Return error message
        server --> User: Error message
    else Insert successfully
        productInOrder --> server: Return success message
        deactivate productInOrder
        server --> User: Success message
        deactivate server
    end

end
@enduml